# name: End-to-end tests
# on: push
# jobs:
#   cypress-run:
#     runs-on: ubuntu-22.04
#     strategy:
#       # don't fail the entire matrix on failure
#       fail-fast: false
#       matrix:
#         # run copies of the current job in parallel
#         containers: [1, 2, 3, 4, 5]
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4
#       # Install npm dependencies, cache them correctly
#       # and run all Cypress tests
#       - name: Cypress run
#         uses: cypress-io/github-action@v6
#         env:
#           # For recording and parallelization to work you must set your CYPRESS_RECORD_KEY
#           # in GitHub repo → Settings → Secrets → Actions
#           CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
#           # Creating a token https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       - name: Run Super-Linter
#         uses: super-linter/super-linter@v5
#         env:
#           VALIDATE_ALL_CODEBASE: false
#           DEFAULT_BRANCH: main
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       # after the test run completes store videos and any screenshots
#       - uses: actions/upload-artifact@v3
#         # add the line below to store screenshots only on failures
#         # if: failure()
#         with:
#           name: cypress-screenshots
#           path: cypress/screenshots
#           if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`
#       - uses: actions/upload-artifact@v3
#         with:
#           name: cypress-videos
#           path: cypress/videos
#           if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`
